name: "bug report"
description: "report bugs"
title: '[BUG]: '
labels: "bug"
projects: "randomusert/5"
body:
 - type: markdown
   attributes:
     value: "please report the bug"
 - type: textarea
   id: what_happened
   attributes:
     label: what happened?
     description: what did you expect to see?
     placeholder: what you see?
     value: "i see a bug"
  validitation:
     required: true
